[package]
name = "pixie_kv"
version = "0.1.0"
edition = "2021"

[dependencies]
heapless = { version = "0.8.0", features = ["serde"]}
serde = {version = "1.0", default-features = false, features = ["derive"]}
embedded-io = "0.6.1"
postcard = "1.0.2"
